### ISSUE TITLE
Units disappearing again

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#100]
![units](https://user-images.githubusercontent.com/942488/174669021-778bc366-6ae9-47eb-a7fe-b6d611ec2774.png)

currencies, percentage, etc.

**Comment by D063520** [comment]
Hi!

Since this is coming and going, I would rather wait for the next release and hope it will go away. I fear that I would invest a lot of time debugging and we do not have so much out of it ...

**Comment by D063520** [comment]
@madewild we did an upgrade, do you still see this?

**Comment by madewild** [comment]
No seems good, except that "55.0 percentage" should be "55.0 percent" (on https://linkedopendata.eu/wiki/Item:Q101496 for instance)

https://linkedopendata.eu/wiki/Item:Q660 label is "percentage" while https://www.wikidata.org/wiki/Q11229 is "percent" which is correct. We should re-sync it with Wikidata. I tried with import_one but I currently have a dependency issue with Python 3.11 and Pywikibot, can you do it @D063520 ?
