### ISSUE TITLE
SPARQL queries are slow

### ISSUE THREAD

**Issue by VladimirAlexiev** [ec-doris/EuKnowledgeGraph#103]
This query is quite slow: once 50s, then 5-6s
```sparql
select ?x ?xLabel {
  ?x wdt:P35 wd:Q9934
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} limit 100 offset 200
```

The query is very simple and should return in under 0.5s.
Maybe `wikibase:label` is slowing it down?

Do you guys have some performance monitoring?

**Comment by D063520** [comment]
Hi,

this is probably a problem of blazegraph and the service clause. This is rather a problem to report to wikimedia. As an alternative use:

https://query.linkedopendata.eu/#select%20%3Fx%20%3FxLabel%20%7B%0A%20%20%3Fx%20wdt%3AP35%20wd%3AQ9934%20.%0A%20%20%20%3Fx%20rdfs%3Alabel%20%3FxLabel%20.%0A%20%20FILTER%20%28lang%28%3FxLabel%29%3D%22en%22%29%0A%20%20%23SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D%20limit%20100%20offset%20200

this will take only 200 ms.

**Comment by VladimirAlexiev** [comment]
I read somewhere that `wikibase:label` slows this down, but I didn't think it's such a drastic difference.
@D063520 Maybe you could:
- add a Querying page with some advice (to grow in time)
- Check that example queries don't use `wikibase:label`
