### ISSUE TITLE
consider using Phabricator

### ISSUE THREAD

**Issue by VladimirAlexiev** [ec-doris/EuKnowledgeGraph#106]
I like the Github tracker, and it's extremely widely used.

However, https://phabricator.wikimedia.org/ is a better tracker when it comes to Wikipedia/Wikidata projects.
- It has much richer functionality
- You can link to other WD issues (eg when you're tracking an upstream fix)
- If you enable the `phab` macro, tickets can be referenced in wiki pages

I'm pretty sure they would welcome a new project to be added there.
Eg Salgo60 posted a whole bunch of very detailed issues with shots and checklists, trying to fix things with Europeana (https://phabricator.wikimedia.org/T243907 is one example): the phabricator hosts didn't complain.

The downside is that there's already plenty of info in this tracker.

**Comment by D063520** [comment]
After internal discussion we decided to keep github as a issue tracking service. We are interlinking issues also with our devops repos.
