### ISSUE TITLE
Missing apostrophes

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#11]
Apostrophes are stripped in French, probably because they are treated as single quotes

Example: https://linkedopendata.eu/wiki/Item:Q196755

**Comment by D063520** [comment]
Yes, it is true, for some reason I strip apostrophes:
mylabels[label] = wikidata_item.labels.get(label).replace("\'"," ")
.....

**Comment by D063520** [comment]
ok, does not seam to give errors .... the one entity is fixed. The next run over all entities should fix also other ones

**Comment by madewild** [comment]
Also for properties?

![apos](https://user-images.githubusercontent.com/942488/74409924-21c64b00-4e38-11ea-9321-b39787d5c25b.png)
