### ISSUE TITLE
improve the logo

### ISSUE THREAD

**Issue by VladimirAlexiev** [ec-doris/EuKnowledgeGraph#110]
I don't mean to be disparaging, but have you guys given some good consideration to the logo?
![image](https://user-images.githubusercontent.com/536250/190139634-9cd8fddc-0c73-4b17-a546-60901d0a2c27.png)

- it looks to me a bit like a default abstract image when you don't have an avatar, eg:
![image](https://user-images.githubusercontent.com/536250/190139569-6bdfdbcc-fd2b-4cb4-958a-4c006285ee75.png)

- I don't think it evokes the EU stars logo, if that was the intent
- on the positive side, it looks a bit like a Ukrainian [Vyshyvanka](https://en.wikipedia.org/wiki/Vyshyvanka) and uses the UA colors :-)

slightly related to #98

**Comment by D063520** [comment]
We will not address this issue further
