### ISSUE TITLE
fix  CCI ID links 

### ISSUE THREAD

**Issue by VladimirAlexiev** [ec-doris/EuKnowledgeGraph#111]
The website links in the example here https://linkedopendata.eu/wiki/OpenRefine#Setup do not work.
Eg  https://ec.europa.eu/regional_policy/EN/atlas/programmes/2014-2020/Greece/2014GR16M1OP001.
Please fix them.

Also, add "formatter URL" to the external-id prop `P1367`.
In this way "CCI ID" values (eg https://linkedopendata.eu/wiki/Item:Q2463293#P1367) will be shown as links.
Facilitating access to the extra project info on the EC site is highly valuable.

But I notice that the URLs have different format depending on CCI ID format:
- `Greece/2014GR16M1OP001` vs
- `europe/2014TC16I5CB001`

There are 3 ways to fix this:
- Use the full part "europe/2014TC16I5CB001" as CCI ID
- Use a special redirector that will examine the CCI code and prepend the appropriate prefix (eg GR -> Greece but TC -> europe).
  Such redirector is used eg for "EU VAT" https://www.wikidata.org/wiki/Property:P3608, eg
  https://wikidata-externalid-url.toolforge.org/?p=3608&url_prefix=http://ec.europa.eu/taxation_customs/vies/vatResponse.html?memberStateCode=&id=ATU16274500 ->
  https://ec.europa.eu/taxation_customs/vies/vatResponse.html?memberStateCode=AT&number=U16274500
  (note: currently broken since VIES changed their site)
- Record the full URL at the item, as "official website" or "EC Atlas webpage" or something like that: but the info will be redundant

**Comment by D063520** [comment]
@roberto-musmeci could you please check why these links are not working anymore?

**Comment by D063520** [comment]
The links are working again. It was another service of the EU that had some downtime.

**Comment by VladimirAlexiev** [comment]
@D063520 
Projects with CCI but no URL: https://tinyurl.com/2ektflsf.
4 of these CCI are `TEMPn` so I guess need to be fixed
