### ISSUE TITLE
sample query timeout

### ISSUE THREAD

**Issue by VladimirAlexiev** [ec-doris/EuKnowledgeGraph#113]
https://query.linkedopendata.eu/ , "#Total Budget of Kohesio project by country" gives a timeout
- There are a lot of such projects, so maybe a timeout is warranted. But please check your setup
- If it's warranted, reduce the query to work with a smaller population, or remove it altogether

**Comment by D063520** [comment]
I optimised the query a bit, looks like it does not time out anymore ....
