### ISSUE TITLE
add EU research projects

### ISSUE THREAD

**Issue by VladimirAlexiev** [ec-doris/EuKnowledgeGraph#114]
Could you please add EU research projects?
We worked on the Tracking of Research Results project for DG RTD that analyzed the research output of FP7.
So we have a good idea about all the data below:
- Project with acronym, name, CORDIS ID, DOI, topics, budget, funding, start/finish dates, logo
- Participants with some basic info: name, CORDIS ID (PID), country, city, type
- EU research programmes, calls, topics
- Scientific topics: at least some basic list (OpenAlex inherited the Microsoft Academic "Fields of Science" which is 700k entries, but we're not expecting such depth)
- Project participants, with "sequence in list" and indication of Coordinator role
- Ideally, also project publications, patents and other outcomes. WikiCite has integrated a lot of info on publications in WikiData, and OpenAire may have forced EU participants to submit all their publications metadata, so this is a hard but maybe possible task.
- Ideally, also Authors and their Affiliation at time of publication. This is harder yet, so WikiData has prop "author name string" in addition to "author" that's used as a sort of "staging area".

Here are some sample projects on WD. I've added all Ontotext projects and a few of their participants:
- euBusinessGraph: https://www.wikidata.org/wiki/Q104438316: modest data.
- Tracking of Research Results: https://www.wikidata.org/wiki/Q56259739: richer description. Note: this is a commercial agreement, not a research project.

**Comment by madewild** [comment]
RTD is maintaining a separate CORDIS Knowledge Graph so this is currently out of scope for us... Maybe in the future we will be able to reconcile both but it's big work (remember it's mainly @D063520 and me working on the EU KG, both of us part time ;) )

**Comment by VladimirAlexiev** [comment]
@madewild link please?

**Comment by madewild** [comment]
Unfortunately they keep it private for now... I saw a TRR presentation by RTD last week and they have no plans to make it public in the near future :/

**Comment by VladimirAlexiev** [comment]
TRR made a graph of FP7 research, but the framework programs are much bigger.
@D063520 why not keep this open as an idea (and add it a tag)?
Close means "done" or "we'll never do it", not "we won't do it now".
