### ISSUE TITLE
add some visualizations

### ISSUE THREAD

**Issue by VladimirAlexiev** [ec-doris/EuKnowledgeGraph#115]
For example, here's a graph of Ontotext research projects from https://wikidata.metaphacts.com/resource/wd:Q7095072
![image](https://user-images.githubusercontent.com/536250/190158597-d5cb8972-16a5-491d-89ee-c5b824b60a64.png)
You already have plenty of connected data here, but if #114 is done, the same graph can be recreated based on EuKnowledgeGraph
data.

**Comment by D063520** [comment]
Hi, thank you for pointing to this. There are already some visualizations available like this one:

https://query.linkedopendata.eu/embed.html#%23defaultView%3AGraph%0ASELECT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20VALUES%20%3Fitem%20%7B%20%3Chttps://linkedopendata.eu/entity/Q2515024%3E%7D%20%3Fitem%20%3FpDirect%20%3FlinkTo%20.%0A%20%20OPTIONAL%7B%3Fitem%20rdfs%3Alabel%20%3FitemLabel%20.%0A%20%20FILTER(lang(%3FitemLabel)%3D%22en%22)%7D%0A%7D

<img width="1728" alt="Screenshot 2022-09-14 at 15 25 55" src="https://user-images.githubusercontent.com/10883585/190166589-36439370-cc94-49ad-9f3c-554b4d9d4f82.png">

We currently do not have a business case to add more.

**Comment by VladimirAlexiev** [comment]
This is nice! cheers1
