### ISSUE TITLE
Add redirection in nginx

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#116]
The redirection from https://linkedopendata.eu/prop/direct/P1 to https://linkedopendata.eu/wiki/Property:P1 is broken
@svili can you look at it in the nginx rules or elsewhere?

**Comment by svili** [comment]
There is no NGINX here, I guess it was only part of the EC2 instance. 
So I think this is more appropriate here: https://github.com/ec-doris/gitops-linkedopendata/issues/71

**Comment by madewild** [comment]
Ah yes I did not see it, duplicate
