### ISSUE TITLE
Problem when adding external links on items of the wiki

### ISSUE THREAD

**Issue by Marie-Sparna** [ec-doris/EuKnowledgeGraph#130]
Second time I get the same error when adding a link to the "Declarations" category of an item (source code repository element) : 

![image](https://user-images.githubusercontent.com/122270728/227882880-fdc5ed14-d866-496c-ab73-2aa34f83ecaa.png)

(system failed to register because of an error)

Do I need to write the link in a particular way to avoid getting the error ?

**Comment by D063520** [comment]
Hi,

could you past the link here?

Salut
D063520

**Comment by Marie-Sparna** [comment]
Hi Dennis,

this time it's a link with an anchor :
https://github.com/sparna-git/skos-play#create-skos-classifications-from-excel--google-spreadsheets

But previously I have obtained the same error with a more simple link :
https://github.com/sparna-git/skos-play (and Ivo added the link itself
finally).

I'd have an other question about EU Login credentials, is it possible to
edit my username in the wiki or not ? I tried several times via the special
pages but it appears I can't manage to do it as I have no account already
created in the wiki :(

Thank you in advance for the help !

*Marie Muller* -* SPARNA*
Web de *données* | Architecture de l'*information* | Accès aux
*connaissances*
blog : blog.sparna.fr, site : sparna.fr

**Comment by Marie-Sparna** [comment]
Same problem when adding an external link to newly created items :

![image](https://user-images.githubusercontent.com/122270728/227947950-03332ee6-57c2-459d-b856-9a49b0488a8e.png)

**Comment by D063520** [comment]
This issue seams related to this:

https://phabricator.wikimedia.org/T301243

**Comment by D063520** [comment]
Ok, I think I solved the bug. @Marie-Sparna can you please check?

**Comment by D063520** [comment]
PS: we did not notice before since admins did not have this problem

**Comment by D063520** [comment]
@Marie-Sparna sorry, just trying to isolate issues, what is the problem with "is it possible to edit my username in the wiki or not ?". Your username is assigned via EU Login. You cannot change that identifier. Is this the question?

**Comment by D063520** [comment]
@Marie-Sparna can you close this issue if it works for you?

**Comment by D063520** [comment]
> > @Marie-Sparna sorry, just trying to isolate issues, what is the problem with "is it possible to edit my username in the wiki or not ?". Your username is assigned via EU Login. You cannot change that identifier. Is this the question?
> 
> Yes, tell me if I need to create another issue for that purpose. I was wondering if I could customize my username somewhere to attribute my contributions ?

This is not possible currently. I opened an issue where we try to investigate if this is possible:

https://github.com/ec-doris/EuKnowledgeGraph/issues/131
