### ISSUE TITLE
Adding constraints checking

### ISSUE THREAD

**Issue by D063520** [ec-doris/EuKnowledgeGraph#16]
by putting constrains it is possible to detect errors in the data

**Comment by madewild** [comment]
@D063520 did you work on this or do you want me to investigate?

**Comment by D063520** [comment]
the problem here is to install a plugin .... I think I would do this when we mnigrated to the last version of wikimedia/wikibase .... can you take care of the disk space on the machine?

**Comment by madewild** [comment]
@D063520 can we install this plugin now that we upgraded the wikibase?

**Comment by D063520** [comment]
yes we can, will take care of this .....

**Comment by madewild** [comment]
@D063520 do we keep this open in wait of a better solution/extension?

**Comment by madewild** [comment]
Ivo is also pushing for this... we should raise the topic with WMDE next time we see them.

**Comment by D063520** [comment]
the constrains are activated ... in fact we can close this ...

**Comment by madewild** [comment]
OK...
