### ISSUE TITLE
Wrong label language

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#18]
Some projects have their label linked for the wrong language. For instance https://linkedopendata.eu/wiki/Item:Q232286 is an Irish project with English label, but in English there is "No label defined" because the label was added to Czech!

**Comment by madewild** [comment]
There are 50 Irish projects affected. Query to find them:

```sparql
select * where {
?project <https://linkedopendata.eu/prop/direct/P35> <https://linkedopendata.eu/entity/Q9934> .
?project <https://linkedopendata.eu/prop/direct/P32> <https://linkedopendata.eu/entity/Q2> .
OPTIONAL {?project rdfs:label ?label filter(lang(?label) = 'en') }
OPTIONAL {?project rdfs:label ?labelcs filter(lang(?labelcs) = 'cs') }
 FILTER( !bound( ?label ))
}
```

**Comment by madewild** [comment]
Same for 160 French projects with Polish label : 

select (REPLACE(STR(?project),".*Q","Q") AS ?qid) ?sLabel where {
?project <https://linkedopendata.eu/prop/direct/P35> <https://linkedopendata.eu/entity/Q9934> .
?project <https://linkedopendata.eu/prop/direct/P32> <https://linkedopendata.eu/entity/Q20> .
OPTIONAL {?project rdfs:label ?label filter(lang(?label) = 'fr') }
OPTIONAL {?project rdfs:label ?sLabel filter(lang(?sLabel) = 'pl') }
  FILTER (!bound(?label))
}

**Comment by madewild** [comment]
@D063520 did you see this? can you correct them like this morning for Ireland/Czech? Thanks! :)
All the other English labels are there...

**Comment by D063520** [comment]
took a bit ...
