### ISSUE TITLE
Summary property is multilingual

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#19]
Summaries (https://linkedopendata.eu/wiki/Property:P836) for Ireland are in English, but for other countries they are in country language. Should we create another property "English summary" (and duplicate for Irish projects), or rename "summary" to "original summary"? We need to discuss this.

**Comment by D063520** [comment]
? is english not the offical language of ireland?

**Comment by D063520** [comment]
ah, no, summary is a monolingualtext property, we can translate and put a different language tag!

**Comment by madewild** [comment]
Oh great I didn't know that!! Then we just need to adapt in the pywikibot to be sure that the right language is encoded. :)

**Comment by madewild** [comment]
I finish to translate all the labels before starting with the summaries...

**Comment by D063520** [comment]
Yes, here a code "draft", note monolingual text with the language as second parameter:

```
claim = pywikibot.Claim(wikibase_repo, id.get_id(wikidata_propertyId), datatype='monolingualtext')
target = pywikibot.WbMonolingualText(text=wikidata_text, language=wikidata_language)
claim.setTarget(target)
```

Cool that the translation is working so well now!
