### ISSUE TITLE
Missing geocoordinates

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#20]
More than 5500 French projects have no geocoordinates although they have a postal code : 

```sparql
select * where {
?project <https://linkedopendata.eu/prop/direct/P35> <https://linkedopendata.eu/entity/Q9934> .
?project <https://linkedopendata.eu/prop/direct/P32> <https://linkedopendata.eu/entity/Q20> .
?project <https://linkedopendata.eu/prop/direct/P460> ?postalcode
OPTIONAL{?project <https://linkedopendata.eu/prop/direct/P127> ?coordinates }.
filter (!bound(?coordinates))
}
```

Do we need to restart the Nominatim server?

**Comment by D063520** [comment]
Mhmm, seams like nominatim cannot resolve it, project:

https://linkedopendata.eu/wiki/Item:Q139270

postal code 91107, no french entry:

https://nominatim.openstreetmap.org/search.php?q=91107&polygon_geojson=1&viewbox=

**Comment by D063520** [comment]
google can resolve it:

https://www.google.com/search?client=safari&ei=zv1LXsKtOIaclwT_oKawDw&q=91107+france&oq=91107+france&gs_l=psy-ab.3...3719.4542..4691...0.0..0.83.645.9......0....1..gws-wiz.......0i7i30j0j0i22i30j33i160.KTvtfUK9csI&ved=0ahUKEwjCzLrMsNvnAhUGzoUKHX-QCfYQ4dUDCAo&uact=5

**Comment by madewild** [comment]
Yeah in this case the "real" postal code seems to be 91100

**Comment by D063520** [comment]
the google one is wrong ....

**Comment by madewild** [comment]
I have 300$ of free google cloud credit so I could geocode the 5000 (it would cost about 25$) but if it's wrong there's no use...

**Comment by madewild** [comment]
Here are the top missing postal code with number of occurrences:

45041	437
97100	133
69269	124
97490	115
97122	107
54052	105
25031	92
97232	92
97200	80
60203	78
31406	75
59555	73
63001	73
51724	63
10004	61
97410	59
97744	54
97404	50

**Comment by madewild** [comment]
Maybe they declare their INSEE code by mistake?

https://www.insee.fr/fr/statistiques/1405599?geo=COM-45041

**Comment by madewild** [comment]
3807 French projects still lack geocoordinates...

**Comment by D063520** [comment]
I run the public nominatim on it. This fixed the geo-coordinates out of europe. But the trick with cedex (remove some digits) that we thought didn't work. If you have any other idea how to fix that ....

**Comment by madewild** [comment]
OK will look into it

**Comment by madewild** [comment]
Kohesio issues covered elsewhere
