### ISSUE TITLE
Translating summaries

### ISSUE THREAD

**Issue by D063520** [ec-doris/EuKnowledgeGraph#23]
to english

**Comment by madewild** [comment]
Denmark is done (except Q196500 and Q196504 that don't have a Danish summary).
France is running...

**Comment by D063520** [comment]
Can it be that there is a mistake:

https://linkedopendata.eu/wiki/Item:Q142581

see summary translation

**Comment by madewild** [comment]
Argh indeed, thanks!

**Comment by madewild** [comment]
Denmark corrected, France finished (one single project had an English summary instead of French so I fixed this manually, 1602 projects have no summary at all).
Translating Czech Rep now...

**Comment by madewild** [comment]
All Polish are finally there.
Only Italy is partially missing but I wait until I discuss it with Anne

**Comment by D063520** [comment]
Very good. I'm currently adding a second identifier to the italian projects. This is a really identifiers. It also gives a natural link to the opencoesione website. Once this is done I will import the remaining projects. Hopefully by end of the week we are done ....
