### ISSUE TITLE
Merge fails

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#24]
Q196504 is a duplicate of Q196500 but merge fails with TypeError

**Comment by D063520** [comment]
I think they are not the same .... but the label of one of them was in Polish, now should be fine ... I didn't merge them but I changed the name ....

**Comment by madewild** [comment]
I think they are the same (and we have some issues) because there is only one project with this title in the source DK file...

**Comment by D063520** [comment]
let's discuss in the call ...
