### ISSUE TITLE
Duplicate coordinates

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#25]
Some project have double coordinates with very close (but not equal) values: https://linkedopendata.eu/wiki/Item:Q52975

Some cleanup is required...

**Comment by madewild** [comment]
@D063520 do you want me to link into that?

**Comment by D063520** [comment]
yes, sure! but note that sometimes there are really more then one coordinates, I think in poland they declared multiple location, so it should only adjusted it the coordinates are the same ....
Note also that this is not a problem for the RDF since triples that are the same are just ignored ....
