### ISSUE TITLE
Duplicate summaries

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#26]
Wikibase does not check for duplicate summaries in the same language so some projects like https://linkedopendata.eu/wiki/Item:Q518375 have twice the same

We should check and remove these duplicates

**Comment by madewild** [comment]
This one is fixed but it's unclear how many items are affected (only Italy?)

**Comment by D063520** [comment]
This query is doing the job:

select ?s ?c where {
{select ?s (count(?o) as ?c) where {
?s <https://linkedopendata.eu/prop/direct/P836> ?o .
FILTER (lang(?o)="en")
} group by ?s }
  FILTER(?c >1)
}

But there is no one!!!! I added a second english summary for one item, the query was returning it back. So my conclusion is that the data is clean with this respect ....

**Comment by madewild** [comment]
Unfortunately not, look here: https://linkedopendata.eu/wiki/Item:Q112286

There is also a problem with the neural translation stuck in a loop, I reported it to eTranslation

**Comment by madewild** [comment]
(my script just removed a lot of duplicates for Poland)

**Comment by D063520** [comment]
wait ... I thought the problem is that you inserted two times the property with english summary, the one you pasted is differently ... or ?

**Comment by madewild** [comment]
No no it was exactly the same (look at https://linkedopendata.eu/w/index.php?title=Item:Q112286&action=history) but now it was removed at 11:49 it so you cannot see anymore that it was not detected by your query. Let me find another one outside Poland...

**Comment by madewild** [comment]
Here is one: https://linkedopendata.eu/wiki/Item:Q518376

The duplicate summary is still there but not detected by your query

**Comment by D063520** [comment]
I think we have a problem ..... no sparql query will see it because duplicate triples are not indexed in a triplestore .....

**Comment by madewild** [comment]
OK then I need to iterate over the whole wikibase with my duplicate-removal script...

**Comment by D063520** [comment]
to reduce it a bit, you can iterate over all entities that have an english summary ..... still a lot

**Comment by madewild** [comment]
Yeah annoying, for labels pywikibot was preventing these duplicates but there is no check for other properties... They get different wikibase IDs:

Claim.fromJSON(DataSite("my", "my"), {'mainsnak': {'snaktype': 'value', 'property': 'P836', 'datatype': 'monolingualtext', 'datavalue': {'value': {'text': '5 — INTERNSHIP, INCLUDING IN TERMS OF GEOGRAPHY', 'language': 'en'}, 'type': 'monolingualtext'}}, 'type': 'statement', 'id': '**Q518375$4e993a8d-8077-4573-9620-43467d2a411e**', 'rank': 'normal'})

Claim.fromJSON(DataSite("my", "my"), {'mainsnak': {'snaktype': 'value', 'property': 'P836', 'datatype': 'monolingualtext', 'datavalue': {'value': {'text': '5 — INTERNSHIP, INCLUDING IN TERMS OF GEOGRAPHY', 'language': 'en'}, 'type': 'monolingualtext'}}, 'type': 'statement', 'id': '**Q518375$9bd9d6c8-945d-4eb5-a711-53d534bad0e1**', 'rank': 'normal'})

**Comment by D063520** [comment]
There is this ticket ... but seams that they want to keep it
https://phabricator.wikimedia.org/T48293

**Comment by madewild** [comment]
I put a safety check to avoid that it happens again but we still have to cleanup...

**Comment by madewild** [comment]
For France:
Removing duplicate summary for Q141663
Removing duplicate summary for Q141717
Removing duplicate summary for Q149541
Removing duplicate summary for Q149542

For Denmark:
Removing duplicate summary for Q2100750
Removing duplicate summary for Q2100750
Removing duplicate summary for Q2100751
Removing duplicate summary for Q2100813
Removing duplicate summary for Q2100928
