### ISSUE TITLE
Add programme

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#27]
[TDE] Dans le fichier italien, c’est la colonne OC_CODICE_PROGRAMMA.  
Dans le fichier français, c’est la colonne Programme.
Dans le fichier belge, c’est la colonne Operational program.
En règle générale, 
le programme est spécifié explicitement lorsqu’on va chercher le fichier national des opérations.
Le programme est connu implicitement lorsqu’on va chercher le fichier régional des opérations :

**Comment by D063520** [comment]
is there somewhere a list of all programs with the translations? To make proper entities out of them ...

**Comment by madewild** [comment]
Here I guess: https://ec.europa.eu/regional_policy/en/atlas/programmes/
But we should ask for a better export

**Comment by D063520** [comment]
I'm currently adding the program to Italy. For the other countries I cannot find the program. Waiting for Therry ....

**Comment by madewild** [comment]
He said that for France it is in the Programme column which is the first one. However, they use a different format (FEDER = ERDF) so I guess we need a manual mapping, annoying...

**Comment by D063520** [comment]
wonderfull!

**Comment by madewild** [comment]
I think we are overloading the Wikibase, the endpoint seems to be down...
