### ISSUE TITLE
Adding rendering of images

### ISSUE THREAD

**Issue by D063520** [ec-doris/EuKnowledgeGraph#3]

**Comment by D063520** [comment]
This depends on this task:

https://phabricator.wikimedia.org/T240751

**Comment by madewild** [comment]
They did not reply to your last comment of February 13, maybe we should ping them again?

**Comment by madewild** [comment]
I saw your https://phabricator.wikimedia.org/T249263 update
They do not seem so keen on fixing that soon...

**Comment by D063520** [comment]
yes ... we need to organize this wikidata meeting!

**Comment by madewild** [comment]
Status to check with WMDE in January meeting

**Comment by D063520** [comment]
waiting for this:

https://phabricator.wikimedia.org/T240751
