### ISSUE TITLE
Retrieve postal codes where missing

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#34]
Can be tricky...

**Comment by D063520** [comment]
In fact if the postal code is not there we need to compute it, meaning given the geo-coordinate we need to reverse geo-compute it. Meaning nominatim for everywhere where it is missing ...

There are only 60.000 now:

https://query.linkedopendata.eu/#select%20%28count%28%3Fs%29%20as%20%3Fc%29%20where%20%7B%0A%3Fs%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP460%3E%20%3Fo%0A%7D

There were only in Czech Rep and maybe denmark and ireland ....

Is it worth doing that?

**Comment by madewild** [comment]
That seems a lot of work so let's put it on hold unless it's really needed...
