### ISSUE TITLE
Some translations missing?

### ISSUE THREAD

**Issue by D063520** [ec-doris/EuKnowledgeGraph#35]
Hi Max,

I'm not sure if I made a mistake ... can you check this item:

https://linkedopendata.eu/wiki/Item:Q9604

it seams to not have an Enlish label? Was it there at any time, I cannot find it in the history ...

**Comment by madewild** [comment]
Strange, I have 333 of them... I thought everything was done, I will cross check for other countries.

**Comment by madewild** [comment]
OK all EN labels for Czech projects should be there now

**Comment by madewild** [comment]
France had 166 missing as well, importing now
Maybe I did a mistake during my first import, now it's more robust

**Comment by madewild** [comment]
Other countries are OK, thanks for spotting this
