### ISSUE TITLE
Increase timeout to more the 60 s

### ISSUE THREAD

**Issue by D063520** [ec-doris/EuKnowledgeGraph#36]

**Comment by madewild** [comment]
This is still annoying for complex queries on Italy... Any update?

**Comment by D063520** [comment]
mhmmm .... since the enpoint is public I would rather leave it like this, otherwise someone can easily crash it no? I would rather use the QAnswer endpoint for this ... would that be fine?

**Comment by madewild** [comment]
Even an increase to 90 seconds? But if the other endpoint is available (where exactly?) why not

**Comment by madewild** [comment]
Working fine with alternative endpoint.
