### ISSUE TITLE
Wrong display of maps

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#43]
Maps are not displayed correctly

See https://linkedopendata.eu/wiki/Item:Q77409 for instance

**Comment by madewild** [comment]
Answer from Jens Ohlig:

The errors you're getting are due to the MediaWiki extension Kartographer https://www.mediawiki.org/wiki/Extension:Kartographer

Currently, Kartographer relies on the Wikimedia Foundation's tile server for OpenStreetMap and this tile server is reserved for Wikimedia projects.

There are some steps that can be taken, but they may need further investigation.

It is possible to turn off Kartographer:
1. Set "useKartographerGlobeCoordinateFormatter" to "false"
2. Set "useKartographerMaplinkInWikitext" to "false"

However, this would turn off the map functionality.

We are currently not sure how flexible Kartographer is when it comes to using alternative tile services.

There are free tile servers available that can be used, but that would mean further investigation: https://wiki.openstreetmap.org/wiki/Tile_server

**Comment by D063520** [comment]
I made an ugly fix. So it is rendering (not the tile though). We need to wait for this:

https://phabricator.wikimedia.org/T259868

**Comment by D063520** [comment]
This seams to be fixed. I can try to update Kartographer. Waiting for deployment on the cluster

**Comment by madewild** [comment]
OK nice, I did some updates in the npm package.json and package-lock.json files (vulnerabilities in Kartograher and JsonConfig extensions) so it would be a good time to patch them both to the latest version.
