### ISSUE TITLE
Open external links in new tab?

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#50]
Links on https://linkedopendata.eu/wiki/Project:About open in same window/tab and quit Wikibase.

We can use $wgExternalLinkTarget = '_blank'; in the LocaleSettings

**Comment by D063520** [comment]
Can you check this again? I do not feel we are quitting Wikibase

**Comment by D063520** [comment]
Is fixed in dev:

https://dev.linkedopendata.eu/wiki/Project:About

**Comment by madewild** [comment]
Great!
@raphdom now we need this on the cluster as well ;)
