### ISSUE TITLE
Upgrade to MW 1.38

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#53]
Or keep LTS version?

**Comment by madewild** [comment]
Also check https://www.mediawiki.org/wiki/2021-12_security_release/FAQ

**Comment by D063520** [comment]
We currently have 1.35 .... apparently we should at least upgrade to 1.35.5. If we need to upgrade I think it is easier to upgrade everything ...., we tacke the new docker container of wikimedia and then we are done .... what do you think>

**Comment by madewild** [comment]
Yes, if we need an upgrade anyway better go straight to 1.37... unless it breaks something!

**Comment by D063520** [comment]
I do not think, the question is more when and how to do it .... the easiest for me would be, you clone the prod machine and I try it out there, then I do it on prod. Or I do it on prod on the weekend and we will have downtimes of unexpected things

**Comment by madewild** [comment]
Let's go for a clone then!

**Comment by madewild** [comment]
Don't know if you're still in the middle of it but there are strange errors on https://linkedopendata.eu/wiki/Special:Version ;)

**Comment by madewild** [comment]
Let's wait until we have 1.38 LTS now.
