### ISSUE TITLE
Change Wikidata logo

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#56]
When going to https://query.linkedopendata.eu/embed.html#%23defaultView%3AGraph%0ASELECT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20VALUES%20%3Fitem%20%7B%20%3Chttps://linkedopendata.eu/entity/Q2514074%3E%7D%20%3Fitem%20%3FpDirect%20%3FlinkTo%20.%0A%20%20%3Fitem%20rdfs%3Alabel%20%3FitemLabel%20.%0A%20%20FILTER(lang(%3FitemLabel)%3D%22en%22)%0A%7D for instance, a huge Wikidata logo is shown during the loading time.

It gives the user the false impression that we are on Wikidata rather than on a distinct Wikibase. Is there a way to change that?

**Comment by D063520** [comment]
This was fixed with the latest release.
