### ISSUE TITLE
Migrate Wikibase to EKS cluster

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#57]
Complexity to evaluate after Kohesio launch...

**Comment by madewild** [comment]
@svili you could also help with this...

**Comment by D063520** [comment]
The code for this is here:

https://github.com/ec-doris/EuKnowledgeGraph/tree/dev

in DEV

**Comment by D063520** [comment]
we can close this right?

**Comment by madewild** [comment]
Indeed :)
