### ISSUE TITLE
Expose full dumps again

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#58]
https://data.linkedopendata.eu/ is currently showing Kohesio data only
this will be moved to https://kohesio.ec.europa.eu/data
At some point we shoud add back the nt triples etc. (full Wikibase export) like Wikidata does

**Comment by madewild** [comment]
This is already the case on https://data.linkedopendata.eu/ but currently not updated (latest dump is 13 March).
@D063520 I thought we set up a cron job to do it every 2 or 3 days?

**Comment by madewild** [comment]
They seem to work but some are failing (today for instance)... need to investigate more?

**Comment by D063520** [comment]
I think the gap was happening when we touched the wikibase and the process was interrupted.
