### ISSUE TITLE
Improve query example

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#61]
On https://query.linkedopendata.eu/
Examples are about NY/US and not EU
Also decouple more from Wikidata...

**Comment by hejjoe** [comment]
Yes, it would be cool to have some good example queries on https://query.linkedopendata.eu, which are specific for the Kohesio project. These example queries could showcase the value of the Kohesio dataset.

**Comment by madewild** [comment]
Wikidata examples have been removed from https://query.linkedopendata.eu/.
@D063520 can you make sure we have a few nice examples about Kohesio there? Then we can close this.

**Comment by madewild** [comment]
Ah it was already done, cache issue on my side...

**Comment by D063520** [comment]
@hejjoe: if you want to can checkout the new feature .... if you have some query that you would like to have, feel free to share here!
