### ISSUE TITLE
Recent changes API timing out when logged in

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#67]

**Comment by D063520** [comment]
Mhmmm ... the problem is that it is working for me
What are the steps to reproduce? can you try with another browser? are you on a special network?

**Comment by madewild** [comment]
Home network (normal wifi), same behaviour with Chromium and Firefox.
Currently it does not time out but still very slow:

- when clicking "Recent changes" in the left pane from the homepage, around 20 seconds to load
- when deselecting "Human (non-bot)", 35 more seconds to reload

If I try the same why not logged in, it takes less than a second for both...

**Comment by D063520** [comment]
@madewild we did an upgrade, could you try to see if this is still happening?

**Comment by madewild** [comment]
Still a bit slow to load when logged in (~10 seconds) but acceptable so let's close
