### ISSUE TITLE
updates not carried over from Wikidata

### ISSUE THREAD

**Issue by D063520** [ec-doris/EuKnowledgeGraph#7]

**Comment by madewild** [comment]
@D063520 what does that mean exactly? still an issue?

**Comment by D063520** [comment]
I need to put in place a script that when a change in wikidata is made, this change is automatically carried over to the wikibase ..... put it a bit on hold since it is not to urgent ....

**Comment by D063520** [comment]
this should work now, updates are carried over with a delay of 5 MINUTES. Cool!!!!!
