### ISSUE TITLE
Map preview missing

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#71]
Go to any project like https://linkedopendata.eu/wiki/Item:Q77409

Coordinates are displayed but the map preview is absent:
![coordinates](https://user-images.githubusercontent.com/942488/160566965-5c3aeeb1-5a3d-478e-b5f6-542adb6634f8.png)

I guess this is since the upgrade...

**Comment by D063520** [comment]
Is fixed now ....

**Comment by D063520** [comment]
Fixed also on the kluster
