### ISSUE TITLE
Identifiers section wrongly labeled

### ISSUE THREAD

**Issue by D063520** [ec-doris/EuKnowledgeGraph#9]
The identifiers are now in a new section, but the section has a bad label "wikibase-statementsection-identifiers”. This is a bug in wikibase and the corresponding ticket is at:
 
https://phabricator.wikimedia.org/T240189

**Comment by madewild** [comment]
It was marked as resolved on December 21, what's the status on our side?

**Comment by D063520** [comment]
I need to find out how to redeploy the wikibase with the latest version. Bit afraid of it .... we need to be sure to not loose any data .... 
-backup
-redeploy
-test
For this could you increase the disk on the amazon machine, or add a volume?

**Comment by madewild** [comment]
Resize an existing volume is always risky... adding a volume should not be a problem. What size should I put?

**Comment by D063520** [comment]
500 Gb? I think that would be ok for now ....

**Comment by madewild** [comment]
OK will do

**Comment by madewild** [comment]
It's there on /newvolume

```Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G  1.4M  1.6G   1% /run
/dev/nvme0n1p1  146G  106G   40G  73% /
tmpfs           7.8G     0  7.8G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/loop1       18M   18M     0 100% /snap/amazon-ssm-agent/1480
tmpfs           1.6G     0  1.6G   0% /run/user/1000
/dev/loop4       92M   92M     0 100% /snap/core/8592
/dev/loop3       92M   92M     0 100% /snap/core/8689
/dev/loop0       18M   18M     0 100% /snap/amazon-ssm-agent/1566
/dev/nvme1n1    492G   73M  467G   1% /newvolume
```

**Comment by D063520** [comment]
ok, I will take care of this once the import of the programs is finished. Currently importing poland and france. Then it is done ....

**Comment by D063520** [comment]
I updated the wikibase instance to 1.34. Unfortunately this does not suffice, this bug is solved only in the current master. I asked:
1) how to deploy the latest?
2) if it is wise to install latest on a production scenario like we have

https://phabricator.wikimedia.org/T249263

We need to find a way to do a workshop with Wikidata people! They us giving us support in the blue (i.e. they have no clue about what we are doing)

**Comment by madewild** [comment]
@D063520 so not yet solved?

**Comment by D063520** [comment]
at that time I came to the conclusion that it is better to wait until a new release .... and now there is a new release ....  1.35. I will try to install it one evening or on the weekend ....

**Comment by D063520** [comment]
now that we are on 1.35 this is done. Wow an issue we opened 1 year ago!
