### ISSUE TITLE
favicon not working with some browsers

### ISSUE THREAD

**Issue by D063520** [ec-doris/EuKnowledgeGraph#98]
<img width="1405" alt="Screenshot 2022-06-01 at 11 33 55" src="https://user-images.githubusercontent.com/10883585/171374243-192a1b17-b900-4206-9016-a28bdafb0945.png">

**Comment by VladimirAlexiev** [comment]
Same here:
![image](https://user-images.githubusercontent.com/536250/190133097-c6f91155-d0af-438d-a5bd-ea7f483cadfd.png)

Chrome Version 105.0.5195.102 (Official Build) (64-bit) on Windows 10

**Comment by D063520** [comment]
This should be fixed
